# Generated by Django 3.1.3 on 2020-11-30 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=45)),
                ('age', models.IntegerField()),
                ('passport', models.CharField(max_length=45)),
                ('min_comfort', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('power', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('passenger_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.passenger')),
                ('train_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.train')),
            ],
        ),
        migrations.AddField(
            model_name='train',
            name='passengers',
            field=models.ManyToManyField(through='api.Trip', to='api.Passenger'),
        ),
        migrations.CreateModel(
            name='Luggage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('height', models.IntegerField()),
                ('length', models.IntegerField()),
                ('passenger_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.passenger')),
            ],
        ),
        migrations.CreateModel(
            name='Carriage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('power', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('height', models.IntegerField()),
                ('maxPassengers', models.IntegerField()),
                ('maxLuggage', models.IntegerField()),
                ('comfort', models.IntegerField()),
                ('type', models.CharField(max_length=45)),
                ('train_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.train')),
            ],
        ),
    ]
